'use strict';
const tribeNames=['Tapang','Dangal','Hiwaga','Exile Island'];
let players=[],teams=[[],[],[],[]],drawing=false,nextId=1;
const $=id=>document.getElementById(id);
function randomInt(max){const a=new Uint32Array(1),limit=Math.floor(4294967296/max)*max;do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%max}
function shuffle(values){const a=[...values];for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function allocate(pool){const order=shuffle([0,1,2]),tribeSlots=Math.floor(pool.length/3)*3;return shuffle(pool).map((player,i)=>({player,tribe:i<tribeSlots?order[i%3]:3}))}
function renderTeams(){teams.forEach((team,i)=>{const list=$('team-'+i);list.replaceChildren();team.forEach(p=>{const li=document.createElement('li');li.textContent=p.name;list.append(li)});$('count-'+i).textContent=team.length+' '+(team.length===1?'member':'members')})}
function renderPool(){const container=$('players');container.replaceChildren();if(!players.length){const p=document.createElement('p');p.className='pool-empty';p.textContent='No castaways yet. Add your first player below.';container.append(p)}players.forEach(p=>{const chip=document.createElement('span');chip.className='chip';const name=document.createElement('span');name.textContent=p.name;const remove=document.createElement('button');remove.textContent='×';remove.type='button';remove.setAttribute('aria-label','Remove '+p.name);remove.disabled=drawing;remove.onclick=()=>removePlayer(p.id);chip.append(name,remove);container.append(chip)});$('pool-count').textContent=players.length;$('draw').disabled=drawing||!players.length;$('add').disabled=drawing;$('name').disabled=drawing}
function invalidate(){teams=[[],[],[],[]];renderTeams();$('draw').innerHTML='<span>✦</span> Draw the tribes';$('status').textContent=players.length?players.length+' castaways ready for their next chapter.':'The adventure starts with your players.';renderPool()}
function addPlayers(raw){if(drawing)throw Error('Wait for the draw to finish.');if(typeof raw!=='string')throw Error('Enter player names as text.');const names=raw.split(/[,\n\r]+/).map(s=>s.trim()).filter(Boolean);if(!names.length)throw Error('Enter at least one player name.');if(names.some(n=>n.length>80))throw Error('Please keep each name under 81 characters.');if(names.length+players.length>300)throw Error('The pool can hold up to 300 players.');names.forEach(name=>players.push({id:nextId++,name}));invalidate();return {count:players.length}}
function removePlayer(id){if(drawing)throw Error('Wait for the draw to finish.');if(!players.some(p=>p.id===id))throw Error('Player not found.');players=players.filter(p=>p.id!==id);invalidate()}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function draw(){if(drawing||!players.length)throw Error('Add players and wait for any current draw to finish.');drawing=true;teams=[[],[],[],[]];renderTeams();renderPool();$('draw').textContent='Drawing the tribes…';const schedule=allocate(players),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;try{for(const {player,tribe} of schedule){if(!reduced)await pause(Math.min(430,6500/players.length));teams[tribe].push(player);const li=document.createElement('li');li.textContent=player.name;$('team-'+tribe).append(li);$('count-'+tribe).textContent=teams[tribe].length+' '+(teams[tribe].length===1?'member':'members');$('status').textContent=player.name+' joins '+tribeNames[tribe]+'!';document.querySelectorAll('.tribe').forEach((el,i)=>el.classList.toggle('active-tribe',tribe===i))}$('status').textContent='The tribes are set. Your adventure begins.';if(!reduced)celebrate();return teams.map((members,i)=>({tribe:tribeNames[i],members:members.map(p=>p.name)}))}finally{drawing=false;document.querySelectorAll('.tribe').forEach(el=>el.classList.remove('active-tribe'));$('draw').innerHTML='<span>✦</span> Draw again';renderPool()}}
function celebrate(){for(let i=0;i<65;i++){const bit=document.createElement('i');bit.className='spark';bit.style.left=Math.random()*100+'%';bit.style.background=['#ebbf70','#f47754','#82ca78','#ba93ee'][i%4];bit.style.animationDelay=Math.random()*.5+'s';$('sparks').append(bit);setTimeout(()=>bit.remove(),2600)}}
$('entry').addEventListener('submit',e=>{e.preventDefault();try{addPlayers($('name').value);$('name').value='';$('name').focus()}catch(error){$('status').textContent=error.message}});$('draw').addEventListener('click',()=>draw().catch(error=>{$('status').textContent=error.message}));
if(document.modelContext?.registerTool){for(const tool of [{name:'read_tribe_draw',description:'Read the current player pool and tribe assignments.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({players,teams,drawing})},{name:'add_castaways',description:'Add comma-separated or newline-separated player names to the pool. Clears any existing draw.',inputSchema:{type:'object',properties:{names:{type:'string'}},required:['names'],additionalProperties:false},execute:input=>addPlayers(input.names)},{name:'draw_tribes',description:'Randomly form three equal tribes, put remaining players on Exile Island, and show the reveal.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>draw()}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}

